[package]
name = "oop_viewer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "oop_viewer"
path = "src/main.rs"

[dependencies]
petgraph = "0.6.5"
eframe = "0.28"
egui = "0.28"
egui_graphs = "0.21"
